<a href="https://colab.research.google.com/github/kim3076/MachineLearningPython/blob/master/data_processing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Data** **Processing**









Importing libraries 
> *numpy*

>*pandas*

> *pyplot*













In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

Importing dataset


> *Using pd.read_csv + iloc*

> *X : independent variable*
 
> *y : dependent variable*







In [ ]:
dataset = pd.read_csv('Data.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values


In [ ]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [ ]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


Missing data

> *SimpleImputer*



In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy = 'mean')
X[:, 1:3] = imputer.fit_transform(X[:, 1:3])

In [ ]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


Decimal Adjusted

In [ ]:
for i in range(0, len(X)) :
  for j in range(1,3) :
      X[i][j] = np.round(X[i][j], decimals = 1)
    

print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.8]
 ['France' 35.0 58000.0]
 ['Spain' 38.8 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]



Encoding Categorical data

> *OneHotEncoder + ColumnTransformer*



In [ ]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [0])], remainder = 'passthrough')
X = ct.fit_transform(X)

print(X)

[[0.0 1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 1.0 0.0 40.0 63777.8]
 [0.0 1.0 0.0 0.0 35.0 58000.0]
 [1.0 0.0 0.0 1.0 38.8 52000.0]
 [0.0 1.0 0.0 0.0 48.0 79000.0]
 [1.0 0.0 1.0 0.0 50.0 83000.0]
 [0.0 1.0 0.0 0.0 37.0 67000.0]]


Same but using LabelEncoder

In [ ]:
#from sklearn.preprocessing import LabelEncoder
#X[:, 0]= LabelEncoder().fit_transform(X[:, 0]) 
#print(X)

[[1 0.0 0.0 44.0 72000.0]
 [0 0.0 1.0 27.0 48000.0]
 [0 1.0 0.0 30.0 54000.0]
 [0 0.0 1.0 38.0 61000.0]
 [0 1.0 0.0 40.0 63777.8]
 [1 0.0 0.0 35.0 58000.0]
 [0 0.0 1.0 38.8 52000.0]
 [1 0.0 0.0 48.0 79000.0]
 [0 1.0 0.0 50.0 83000.0]
 [1 0.0 0.0 37.0 67000.0]]


Label Encoder for y

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
print(y)

[0 1 0 0 1 1 0 1 0 1]


Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)
print(X_train)
print('Then')
print(X_test)

[[1.0 0.0 0.0 1.0 38.8 52000.0]
 [1.0 0.0 1.0 0.0 40.0 63777.8]
 [0.0 1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 0.0 48.0 79000.0]
 [1.0 0.0 1.0 0.0 50.0 83000.0]
 [0.0 1.0 0.0 0.0 35.0 58000.0]]
Then
[[1.0 0.0 1.0 0.0 30.0 54000.0]
 [0.0 1.0 0.0 0.0 37.0 67000.0]]


Feature scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 4:] = sc.fit_transform(X_train[:, 4:])
print(X_train)
print('Then')
X_test[:, 4:] = sc.transform(X_test[:, 4:])
print(X_test)

[[1.0 0.0 0.0 1.0 -0.188782867067844 -1.0781261965508209]
 [1.0 0.0 1.0 0.0 -0.014521759005218687 -0.07013001344412383]
 [0.0 1.0 0.0 0.0 0.566348601203531 0.6335622055390376]
 [1.0 0.0 0.0 1.0 -0.30495693910959354 -0.3078664156103846]
 [1.0 0.0 0.0 1.0 -1.9023504296836553 -1.4204638769687925]
 [0.0 1.0 0.0 0.0 1.1472189614122807 1.2326531462704882]
 [1.0 0.0 1.0 0.0 1.4376541415166557 1.5749908266884598]
 [0.0 1.0 0.0 0.0 -0.7406097092661559 -0.5646196759238633]]
Then
[[1.0 0.0 1.0 0.0 -0.9999999999999999 -1.0000000000000002]
 [0.0 1.0 0.0 0.0 1.0000000000000004 1.0]]
